(function(){
const day=workoutData.find(d=>d.day===ACTIVE_DAY);if(!day)return;
const exercises=[];day.sections.forEach((s,si)=>s.exercises.forEach((ex,ei)=>exercises.push({ex,si,ei,section:s.name})));
let pos=0,timerId=null,timerTotal=0,timerLeft=0;
const css=document.createElement("style");css.textContent=`
.yg-start{width:100%;margin:0 0 12px;padding:13px;border:1px solid #38bdf8;border-radius:10px;background:#0c315f;color:#fff;font-weight:900;font-size:.9rem}
.yg{position:fixed;inset:0;z-index:4500;display:none;background:#0f172a;overflow:auto;padding:14px}.yg.open{display:block}.yg-card{max-width:650px;margin:auto;background:#1e293b;border:1px solid #334155;border-radius:16px;padding:16px}.yg-top{display:flex;justify-content:space-between;gap:12px;color:#94a3b8;font-size:.78rem;font-weight:800}.yg-x{background:none;border:0;color:#fff;font-size:1.6rem}.yg h2{margin:14px 0 5px}.yg-rx{color:#38bdf8;margin-bottom:12px}.yg-img{background:#fff;border-radius:12px;overflow:hidden;display:flex;justify-content:center;align-items:center;min-height:180px}.yg-img img{display:block;width:100%;height:auto;max-height:48vh;object-fit:contain;background:#fff}.yg-noimg{color:#64748b;padding:30px;text-align:center}.yg-info{color:#cbd5e1;line-height:1.45;margin:12px 0}.yg-cue{color:#fff;font-weight:700}.yg-timer{display:none;margin:12px 0;padding:12px;border:1px solid #38bdf8;border-radius:10px;background:#111827;text-align:center}.yg-timer.show{display:block}.yg-time{font-size:2.4rem;font-weight:900;color:#38bdf8;line-height:1;margin-bottom:10px}.yg-timer-controls{display:flex;justify-content:center;gap:8px;flex-wrap:wrap}.yg-timer button,.yg-actions button{border:1px solid #38bdf8;background:#0f172a;color:#fff;border-radius:9px;padding:11px;font-weight:800}.yg-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.yg-actions .next{background:#38bdf8;color:#0f172a}`;document.head.appendChild(css);
const btn=document.createElement("button");btn.className="yg-start";btn.textContent="START GUIDED SESSION";document.getElementById("routine-container").before(btn);
const modal=document.createElement("div");modal.className="yg";modal.innerHTML='<div class="yg-card"><div class="yg-top"><span id="yg-step"></span><button class="yg-x">×</button></div><h2 id="yg-name"></h2><div class="yg-rx" id="yg-rx"></div><div class="yg-img" id="yg-img"></div><div class="yg-info" id="yg-info"></div><div class="yg-cue" id="yg-cue"></div><div class="yg-timer" id="yg-timer"><div class="yg-time" id="yg-time"></div><div class="yg-timer-controls"><button id="yg-timer-btn"></button><button id="yg-timer-reset">RESET</button></div></div><div class="yg-actions"><button id="yg-back">← BACK</button><button class="next" id="yg-next">COMPLETE →</button></div></div>';document.body.appendChild(modal);
function split(ex){const p=ex.split(/\s+[—–-]\s+/,2);return[p[0],p[1]||""]}
function timerSeconds(ex){const m=ex.match(/(\d+)\s*(sec|min)/i);return m?Number(m[1])*(m[2].toLowerCase()==="min"?60:1):0}
function show(){const o=exercises[pos],p=split(o.ex),info=(typeof movementInfo!=="undefined"&&movementInfo[o.ex])||["Move slowly through a comfortable range with control.","Keep the movement smooth and stop if you feel sharp pain or pinching."];document.getElementById("yg-step").textContent="DAY "+ACTIVE_DAY+" · "+(pos+1)+" / "+exercises.length+" · "+o.section;document.getElementById("yg-name").textContent=p[0];document.getElementById("yg-rx").textContent=p[1];const src=movementImages[o.ex];document.getElementById("yg-img").innerHTML=src?'<img src="'+src+'" alt="">':'<div class="yg-noimg">Image not added yet.</div>';document.getElementById("yg-info").textContent=info[0];document.getElementById("yg-cue").textContent="COACHING CUE: "+info[1];const sec=timerSeconds(o.ex),tb=document.getElementById("yg-timer"),tbtn=document.getElementById("yg-timer-btn");tb.classList.toggle("show",!!sec);if(timerId){clearInterval(timerId);timerId=null}if(sec){timerTotal=timerLeft=sec;const td=document.getElementById("yg-time"),reset=document.getElementById("yg-timer-reset");const paint=()=>{const m=Math.floor(timerLeft/60),s=timerLeft%60;td.textContent=m+":"+String(s).padStart(2,"0")};paint();tbtn.textContent="START TIMER";tbtn.onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;tbtn.textContent="RESUME"}else{tbtn.textContent="PAUSE";timerId=setInterval(()=>{timerLeft--;paint();if(timerLeft<=0){clearInterval(timerId);timerId=null;tbtn.textContent="DONE";if(navigator.vibrate)navigator.vibrate([300,120,300,120,600])}},1000)}};reset.onclick=()=>{if(timerId){clearInterval(timerId);timerId=null}timerLeft=timerTotal;paint();tbtn.textContent="START TIMER"}}const cb=document.getElementById("d"+ACTIVE_DAY+"_s"+o.si+"_e"+o.ei);document.getElementById("yg-next").textContent=cb&&cb.checked?(pos===exercises.length-1?"FINISH":"NEXT →"):(pos===exercises.length-1?"COMPLETE & FINISH":"COMPLETE →");document.getElementById("yg-back").disabled=pos===0}
btn.onclick=()=>{pos=0;modal.classList.add("open");document.body.style.overflow="hidden";show()};modal.querySelector(".yg-x").onclick=()=>{modal.classList.remove("open");document.body.style.overflow=""};document.getElementById("yg-back").onclick=()=>{if(pos>0){pos--;show()}};document.getElementById("yg-next").onclick=()=>{const o=exercises[pos],cb=document.getElementById("d"+ACTIVE_DAY+"_s"+o.si+"_e"+o.ei);if(cb&&!cb.checked){cb.checked=true;onExerciseToggle(ACTIVE_DAY)}if(pos<exercises.length-1){pos++;show()}else{modal.classList.remove("open");document.body.style.overflow=""}};
})();